kind = "DojoContract"
class_hash = "0x6103e99c5ede4c34affd0379761dd4c5beb690d2c51a774ac2b9fa93d0fb079"
original_class_hash = "0x6103e99c5ede4c34affd0379761dd4c5beb690d2c51a774ac2b9fa93d0fb079"
base_class_hash = "0x0"
abi = "manifests/sepolia/abis/base/contracts/pistols_systems_admin_admin.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::systems::admin::admin"
