[tool.dojo.world]
name = "Pistols at 10 Blocks"
description = "An on-chain pistol duelling game of honour and betrayal."
icon_uri = "https://pistols.lootunder.world/images/logo.png"
cover_uri = "https://pistols.lootunder.world/images/splash.png"
website = "https://pistols.lootunder.world"
socials.x = "https://twitter.com/lootunderworld"

[package]
cairo-version = "2.3.1"
name = "pistols"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo.git", rev = "01eab985a3f5056e47cc7b4753ca24f64d3a078a" }
# dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v0.4.2" }


[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
world_address = "0x269c58e5fa1e7f6fe3756f1de88ecdfab7d03ba67e79ba0365b4ef1e81155be"

# Development
rpc_url = "http://localhost:5050/"
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"

# SLOT
# rpc_url = "https://api.cartridge.gg/x/pistols/katana"
# account_address = "0x355df606ef197ceacb60212996047efbef81828f918c8490ac950802dd602b5"
# private_key = "0x5ceca4e52514d4d97217ba3f70d654fff7d6a688c2add4cc7769fbdb17b1aff"
