[tool.dojo.world]
name = "Pistols at 10 Blocks"
description = "An on-chain pistol duelling game of honour and betrayal."
icon_uri = "https://pistols.lootunder.world/images/logo.png"
cover_uri = "https://pistols.lootunder.world/images/splash.png"
website = "https://pistols.lootunder.world"

[tool.dojo.world.socials]
x = "https://x.com/lootunderworld"
github = "https://github.com/funDAOmental/pistols"
# discord = "https://discord.gg/FB2wR6uF"
# telegram = "https://t.me/dojoengine"

[package]
name = "pistols"
version = "0.8.0"
cairo-version = "2.4.0"

[cairo]
sierra-replace-ids = true

[dependencies]
# dojo = { git = "https://github.com/dojoengine/dojo", rev = "01eab985a3f5056e47cc7b4753ca24f64d3a078a" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }
# token = { git = "https://github.com/dojoengine/origami", tag = "v0.6.0" }
# token = { git = "https://github.com/notV4l/origami", branch = "erc_without_events" }
token = { git = "https://github.com/notV4l/origami", rev = "32e225f40f26a1e9729f6baa068ee1b212550080" }


[tool.dojo]
initializer_class_hash = "0xbeef"

[[target.dojo]]
build-external-contracts = [
    "token::components::security::initializable::initializable_model",
    "token::components::token::erc20::erc20_metadata::erc_20_metadata_model",
    "token::components::token::erc20::erc20_balance::erc_20_balance_model",
    "token::components::token::erc20::erc20_allowance::erc_20_allowance_model",
    "token::components::token::erc20::erc20_mintable::erc_20_mintable_model",
    "token::components::token::erc20::erc20_burnable::erc_20_burnable_model",
]

[tool.dojo.env]
world_address = "0x10923ed11da790f94efd6f68c5558f5f604df0ff2ff776bd5209b7ebb8985b8"

[profile.dev.tool.dojo.env]
rpc_url = "http://localhost:5050"
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
lords_address = ""

[profile.slot.tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/pistols-slot/katana"
account_address = "0x23ce913a39de30f729aee781b8dea86281b9a25d897e5d9fb61e3e95cae8cd"
private_key = "0x22372b22b591f4db22860a70e6f831c4eadb80e42669f54ccc7fe2420befea9"
lords_address = ""

[profile.release.tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/realms/katana"
account_address = ""
private_key = ""
lords_address = "0x51205c5e6ac3ad5691c28c0c5ffcdd62c70bddb63612f75a4bac9b2a85b9449"
