[tool.dojo.world]
name = "Pistols at 10 Blocks"
description = "An on-chain pistol duelling game of honour and betrayal."
icon_uri = "https://pistols.lootunder.world/images/logo.png"
cover_uri = "https://pistols.lootunder.world/images/splash.png"
website = "https://pistols.lootunder.world"

[tool.dojo.world.socials]
x = "https://x.com/lootunderworld"
github = "https://github.com/funDAOmental/pistols"
# discord = "https://discord.gg/FB2wR6uF"
# telegram = "https://t.me/dojoengine"

[package]
cairo-version = "2.4.0"
name = "pistols"
version = "0.3.2"

[cairo]
sierra-replace-ids = true

[dependencies]
# dojo = { git = "https://github.com/dojoengine/dojo.git", rev = "01eab985a3f5056e47cc7b4753ca24f64d3a078a" }
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v0.5.1-alpha.5" }


[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
world_address = "0x269c58e5fa1e7f6fe3756f1de88ecdfab7d03ba67e79ba0365b4ef1e81155be"

# Development
rpc_url = "http://localhost:5050/"
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"

# SLOT
# rpc_url = "https://api2.cartridge.gg/x/pistols/katana"
# account_address = "0x2e0e12a0275b03172bb09aafac8e288599678032493fef65adc1af87771bdaa"
# private_key = "0x3cfcac8524dd04d352479c89b5685b9f3b4e788e226305e1df18712154afd76"
