kind = "DojoModel"
class_hash = "0x10134fdb3931edf88cb49604a0d0292a9983b3d680179fec23864058beffcfb"
original_class_hash = "0x10134fdb3931edf88cb49604a0d0292a9983b3d680179fec23864058beffcfb"
abi = "manifests/slot/abis/base/models/pistols_models_models_challenge.json"
name = "pistols::models::models::challenge"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "duelist_a"
type = "ContractAddress"
key = false

[[members]]
name = "duelist_b"
type = "ContractAddress"
key = false

[[members]]
name = "message"
type = "felt252"
key = false

[[members]]
name = "table_id"
type = "felt252"
key = false

[[members]]
name = "state"
type = "u8"
key = false

[[members]]
name = "round_number"
type = "u8"
key = false

[[members]]
name = "winner"
type = "u8"
key = false

[[members]]
name = "timestamp_start"
type = "u64"
key = false

[[members]]
name = "timestamp_end"
type = "u64"
key = false
