[world]
kind = "WorldContract"
class_hash = "0xf6f44afb3cacbcc01a371aff62c86ca9a45feba065424c99f7cd8637514d8f"
original_class_hash = "0xf6f44afb3cacbcc01a371aff62c86ca9a45feba065424c99f7cd8637514d8f"
abi = "manifests/slot/abis/deployments/dojo_world_world.json"
address = "0x509c209fc7c9ad157b463a1b48d92a399239bce020392ab2a920e7f2af31bb5"
transaction_hash = "0x3d75e20c91f9c47d33f9098a7ea3b937479be9a7950ba3ca2cd27fbc41797c2"
block_number = 3
seed = "pistols"
name = "dojo::world::world"

[world.metadata]
profile_name = "slot"
rpc_url = "https://api.cartridge.gg/x/pistols/katana"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0xde77c78f35b39f081eca10228d65e4e5cbc827ed6f1db30539e90e7420900c"
class_hash = "0x6e080db0d09addf181b02489323d3145e03397169492b3ac3e0856e19c46929"
original_class_hash = "0x6e080db0d09addf181b02489323d3145e03397169492b3ac3e0856e19c46929"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/slot/abis/deployments/contracts/pistols_mocks_lords_mock_lords_mock.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::mocks::lords_mock::lords_mock"

[[contracts]]
kind = "DojoContract"
address = "0x34bbde433b8d8cb45ce22d801f4d65a5dcb77b0ef8396d0b5cdc20fc71a1c73"
class_hash = "0x4cc88b2ecd48c3498c4efbcc0922d280fe0241830dd07c8543a16cd64582e37"
original_class_hash = "0x4cc88b2ecd48c3498c4efbcc0922d280fe0241830dd07c8543a16cd64582e37"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/slot/abis/deployments/contracts/pistols_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::systems::actions::actions"

[[contracts]]
kind = "DojoContract"
address = "0x225f690595a067273bdf36583ea9dd91ae2f2fbc78ee2f7480dfcf6b75ba01a"
class_hash = "0x2a79c09b10d04b4cda61e82f4f5d14bd49ea81b360455aee46cf3d6d9e8681e"
original_class_hash = "0x2a79c09b10d04b4cda61e82f4f5d14bd49ea81b360455aee46cf3d6d9e8681e"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/slot/abis/deployments/contracts/pistols_systems_admin_admin.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::systems::admin::admin"

[[models]]
kind = "DojoModel"
class_hash = "0x7c7d28127e68b07de6d798667641b044ed54745a18943aa8fa5d9c0b7883781"
original_class_hash = "0x7c7d28127e68b07de6d798667641b044ed54745a18943aa8fa5d9c0b7883781"
abi = "manifests/slot/abis/deployments/models/pistols_models_config_config.json"
name = "pistols::models::config::config"

[[models.members]]
name = "key"
type = "u8"
key = true

[[models.members]]
name = "initialized"
type = "bool"
key = false

[[models.members]]
name = "owner_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "treasury_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "paused"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x10134fdb3931edf88cb49604a0d0292a9983b3d680179fec23864058beffcfb"
original_class_hash = "0x10134fdb3931edf88cb49604a0d0292a9983b3d680179fec23864058beffcfb"
abi = "manifests/slot/abis/deployments/models/pistols_models_models_challenge.json"
name = "pistols::models::models::challenge"

[[models.members]]
name = "duel_id"
type = "u128"
key = true

[[models.members]]
name = "duelist_a"
type = "ContractAddress"
key = false

[[models.members]]
name = "duelist_b"
type = "ContractAddress"
key = false

[[models.members]]
name = "message"
type = "felt252"
key = false

[[models.members]]
name = "table_id"
type = "felt252"
key = false

[[models.members]]
name = "state"
type = "u8"
key = false

[[models.members]]
name = "round_number"
type = "u8"
key = false

[[models.members]]
name = "winner"
type = "u8"
key = false

[[models.members]]
name = "timestamp_start"
type = "u64"
key = false

[[models.members]]
name = "timestamp_end"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x697c394b9f03f9dfb52b72f313966b5ec04bae949fb83f5e1781bd51b358a8d"
original_class_hash = "0x697c394b9f03f9dfb52b72f313966b5ec04bae949fb83f5e1781bd51b358a8d"
abi = "manifests/slot/abis/deployments/models/pistols_models_models_duelist.json"
name = "pistols::models::models::duelist"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "profile_pic"
type = "u8"
key = false

[[models.members]]
name = "score"
type = "Score"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x41b9f5d9320da8200fa32123dc2388e490cfb628d4469d4d63a3dad628dc06f"
original_class_hash = "0x41b9f5d9320da8200fa32123dc2388e490cfb628d4469d4d63a3dad628dc06f"
abi = "manifests/slot/abis/deployments/models/pistols_models_models_pact.json"
name = "pistols::models::models::pact"

[[models.members]]
name = "pair"
type = "u128"
key = true

[[models.members]]
name = "duel_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7c19533a2d1c38c6827023613ef7b83830ab894b2ba296378a06137ff9705d9"
original_class_hash = "0x7c19533a2d1c38c6827023613ef7b83830ab894b2ba296378a06137ff9705d9"
abi = "manifests/slot/abis/deployments/models/pistols_models_models_round.json"
name = "pistols::models::models::round"

[[models.members]]
name = "duel_id"
type = "u128"
key = true

[[models.members]]
name = "round_number"
type = "u8"
key = true

[[models.members]]
name = "state"
type = "u8"
key = false

[[models.members]]
name = "shot_a"
type = "Shot"
key = false

[[models.members]]
name = "shot_b"
type = "Shot"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2378ffc0f8726c96264becc5efe65a5f68ca4aaa5ed294a04d0e58283190924"
original_class_hash = "0x2378ffc0f8726c96264becc5efe65a5f68ca4aaa5ed294a04d0e58283190924"
abi = "manifests/slot/abis/deployments/models/pistols_models_models_scoreboard.json"
name = "pistols::models::models::scoreboard"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "table_id"
type = "felt252"
key = true

[[models.members]]
name = "score"
type = "Score"
key = false

[[models.members]]
name = "wager_won"
type = "u256"
key = false

[[models.members]]
name = "wager_lost"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2a944262c5784a67297717f50a9179dca0dc8758499818aa053c22aa29d2ea8"
original_class_hash = "0x2a944262c5784a67297717f50a9179dca0dc8758499818aa053c22aa29d2ea8"
abi = "manifests/slot/abis/deployments/models/pistols_models_models_snapshot.json"
name = "pistols::models::models::snapshot"

[[models.members]]
name = "duel_id"
type = "u128"
key = true

[[models.members]]
name = "score_a"
type = "Score"
key = false

[[models.members]]
name = "score_b"
type = "Score"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4d5ef85d815ac09cc85fca98671995dd454d25e156c9ab4bec948122acac445"
original_class_hash = "0x4d5ef85d815ac09cc85fca98671995dd454d25e156c9ab4bec948122acac445"
abi = "manifests/slot/abis/deployments/models/pistols_models_models_wager.json"
name = "pistols::models::models::wager"

[[models.members]]
name = "duel_id"
type = "u128"
key = true

[[models.members]]
name = "value"
type = "u256"
key = false

[[models.members]]
name = "fee"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2d7f48d08a0977e048af24f84c5236b1326b641520ed5a62fe5d4b7e50ae115"
original_class_hash = "0x2d7f48d08a0977e048af24f84c5236b1326b641520ed5a62fe5d4b7e50ae115"
abi = "manifests/slot/abis/deployments/models/pistols_models_table_t_table.json"
name = "pistols::models::table::t_table"

[[models.members]]
name = "table_id"
type = "felt252"
key = true

[[models.members]]
name = "description"
type = "felt252"
key = false

[[models.members]]
name = "contract_address"
type = "ContractAddress"
key = false

[[models.members]]
name = "wager_min"
type = "u256"
key = false

[[models.members]]
name = "fee_min"
type = "u256"
key = false

[[models.members]]
name = "fee_pct"
type = "u8"
key = false

[[models.members]]
name = "is_open"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x43d32948aa1be53f26e75e04da5ec56796f6e86030084b3ebede98c45ace32a"
original_class_hash = "0x43d32948aa1be53f26e75e04da5ec56796f6e86030084b3ebede98c45ace32a"
abi = "manifests/slot/abis/deployments/models/token_components_security_initializable_initializable_model.json"
name = "token::components::security::initializable::initializable_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "initialized"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x304439814dd12e69d7898d226219e2fa2a374e82dae38f902c1b6a706bc8e82"
original_class_hash = "0x304439814dd12e69d7898d226219e2fa2a374e82dae38f902c1b6a706bc8e82"
abi = "manifests/slot/abis/deployments/models/token_components_token_erc20_erc20_allowance_erc_20_allowance_model.json"
name = "token::components::token::erc20::erc20_allowance::erc_20_allowance_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "spender"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x291d91ffdce5772e40317feaf3b43873e8c716716d948b35c77c06c21fa4e9d"
original_class_hash = "0x291d91ffdce5772e40317feaf3b43873e8c716716d948b35c77c06c21fa4e9d"
abi = "manifests/slot/abis/deployments/models/token_components_token_erc20_erc20_balance_erc_20_balance_model.json"
name = "token::components::token::erc20::erc20_balance::erc_20_balance_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x648f87547cad4c7ff85ab3c422f77850b4a6f0b0f1494011440449a52aa8053"
original_class_hash = "0x648f87547cad4c7ff85ab3c422f77850b4a6f0b0f1494011440449a52aa8053"
abi = "manifests/slot/abis/deployments/models/token_components_token_erc20_erc20_metadata_erc_20_metadata_model.json"
name = "token::components::token::erc20::erc20_metadata::erc_20_metadata_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "symbol"
type = "felt252"
key = false

[[models.members]]
name = "decimals"
type = "u8"
key = false

[[models.members]]
name = "total_supply"
type = "u256"
key = false
