kind = "DojoModel"
class_hash = "0x41b9f5d9320da8200fa32123dc2388e490cfb628d4469d4d63a3dad628dc06f"
original_class_hash = "0x41b9f5d9320da8200fa32123dc2388e490cfb628d4469d4d63a3dad628dc06f"
abi = "manifests/sepolia/abis/base/models/pistols_models_models_pact.json"
name = "pistols::models::models::pact"

[[members]]
name = "pair"
type = "u128"
key = true

[[members]]
name = "duel_id"
type = "u128"
key = false
