kind = "DojoModel"
class_hash = "0x33d2265485a3f0d4526c4301252df10ceff481c92664fe3f261ea69e3b31b60"
original_class_hash = "0x33d2265485a3f0d4526c4301252df10ceff481c92664fe3f261ea69e3b31b60"
abi = "manifests/dev/abis/base/models/pistols_models_models_chances.json"
name = "pistols::models::models::chances"

[[members]]
name = "key"
type = "felt252"
key = true

[[members]]
name = "crit_chances"
type = "u8"
key = false

[[members]]
name = "crit_bonus"
type = "u8"
key = false

[[members]]
name = "hit_chances"
type = "u8"
key = false

[[members]]
name = "hit_bonus"
type = "u8"
key = false

[[members]]
name = "lethal_chances"
type = "u8"
key = false

[[members]]
name = "lethal_bonus"
type = "u8"
key = false
