kind = "DojoModel"
class_hash = "0x509bff8af1b70776dad31c1dc7532a2ff1f76ab22bb08d2137978380ecfce9b"
original_class_hash = "0x509bff8af1b70776dad31c1dc7532a2ff1f76ab22bb08d2137978380ecfce9b"
abi = "manifests/dev/abis/base/models/pistols_models_models_duelist.json"
name = "pistols::models::models::duelist"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "profile_pic"
type = "u8"
key = false

[[members]]
name = "total_duels"
type = "u16"
key = false

[[members]]
name = "total_wins"
type = "u16"
key = false

[[members]]
name = "total_losses"
type = "u16"
key = false

[[members]]
name = "total_draws"
type = "u16"
key = false

[[members]]
name = "total_honour"
type = "u32"
key = false

[[members]]
name = "honour"
type = "u8"
key = false

[[members]]
name = "bonus_villain"
type = "u8"
key = false

[[members]]
name = "bonus_trickster"
type = "u8"
key = false

[[members]]
name = "bonus_lord"
type = "u8"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
