kind = "DojoModel"
class_hash = "0x4d5ef85d815ac09cc85fca98671995dd454d25e156c9ab4bec948122acac445"
original_class_hash = "0x4d5ef85d815ac09cc85fca98671995dd454d25e156c9ab4bec948122acac445"
abi = "manifests/dev/abis/base/models/pistols_models_models_wager.json"
name = "pistols::models::models::wager"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "value"
type = "u256"
key = false

[[members]]
name = "fee"
type = "u256"
key = false
