kind = "DojoModel"
class_hash = "0x4f1a2c28708d94b46a6d16210668ace7c6ec20870c899a588b5ff710c22a3e6"
original_class_hash = "0x4f1a2c28708d94b46a6d16210668ace7c6ec20870c899a588b5ff710c22a3e6"
abi = "manifests/dev/abis/base/models/pistols_models_table_table_config.json"
name = "pistols::models::table::table_config"

[[members]]
name = "table_id"
type = "felt252"
key = true

[[members]]
name = "description"
type = "felt252"
key = false

[[members]]
name = "contract_address"
type = "ContractAddress"
key = false

[[members]]
name = "wager_min"
type = "u256"
key = false

[[members]]
name = "fee_min"
type = "u256"
key = false

[[members]]
name = "fee_pct"
type = "u8"
key = false

[[members]]
name = "is_open"
type = "bool"
key = false

[[members]]
name = "table_type"
type = "u8"
key = false
