kind = "DojoModel"
class_hash = "0x35d376427fca9fa5b83ae138826e5b0e5cd29b39034e8029fa33f0b7e624165"
original_class_hash = "0x35d376427fca9fa5b83ae138826e5b0e5cd29b39034e8029fa33f0b7e624165"
abi = "manifests/dev/abis/base/models/pistols_models_models_duelist.json"
name = "pistols::models::models::duelist"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "profile_pic"
type = "u8"
key = false

[[members]]
name = "total_duels"
type = "u16"
key = false

[[members]]
name = "total_wins"
type = "u16"
key = false

[[members]]
name = "total_losses"
type = "u16"
key = false

[[members]]
name = "total_draws"
type = "u16"
key = false

[[members]]
name = "total_honour"
type = "u32"
key = false

[[members]]
name = "honour"
type = "u8"
key = false

[[members]]
name = "villainy"
type = "u8"
key = false

[[members]]
name = "trickery"
type = "u8"
key = false

[[members]]
name = "virtue"
type = "u8"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
