kind = "DojoModel"
class_hash = "0x53e594213e62f41661a15c95038f89ae4c6cefe271eed0350503eee6a7c10b0"
original_class_hash = "0x53e594213e62f41661a15c95038f89ae4c6cefe271eed0350503eee6a7c10b0"
abi = "manifests/dev/abis/base/models/pistols_models_coins_coin.json"
name = "pistols::models::coins::coin"

[[members]]
name = "key"
type = "u8"
key = true

[[members]]
name = "contract_address"
type = "ContractAddress"
key = false

[[members]]
name = "description"
type = "felt252"
key = false

[[members]]
name = "fee_min"
type = "u256"
key = false

[[members]]
name = "fee_pct"
type = "u8"
key = false

[[members]]
name = "enabled"
type = "bool"
key = false
