[package]
cairo-version = "2.4.0"
name = "lords_mock"
version = "0.0.1"

[scripts]
migrate = "sozo build && sozo migrate && ./scripts/default_auth.sh"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.5.1" }
token = { git = "https://github.com/dojoengine/origami", tag = "v0.5.1" }


[tool.dojo]
initializer_class_hash = "0xbeef"

[[target.dojo]]
build-external-contracts = [
    "token::components::security::initializable::initializable_model",
    "token::components::token::erc20::erc20_metadata::erc_20_metadata_model",
    "token::components::token::erc20::erc20_balance::erc_20_balance_model",
    "token::components::token::erc20::erc20_allowance::erc_20_allowance_model",
    "token::components::token::erc20::erc20_mintable::erc_20_mintable_model",
    "token::components::token::erc20::erc20_burnable::erc_20_burnable_model",
    "token::components::token::erc20::erc20_bridgeable::erc_20_bridgeable_model",
]

[tool.dojo.env]
# Development
rpc_url = "http://localhost:5050/"
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"

# SLOT
# rpc_url = "https://api.cartridge.gg/x/pistols/katana"
# account_address = "0x5b7d6d0110aba636b7df1d41858c036aefb8bee9dd4052c51fbf5cd9e2d614"
# private_key = "0x534363549dc5f54179835979add2d508b4a0cb315d9648977aa5f9e363da67a"
