kind = "DojoContract"
class_hash = "0x1020d6597eb85e006b914b60320f134e9dc6614e3c78b61b7ef0858c2e6cde5"
original_class_hash = "0x1020d6597eb85e006b914b60320f134e9dc6614e3c78b61b7ef0858c2e6cde5"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/pistols_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::systems::actions::actions"
