kind = "DojoContract"
class_hash = "0x5554539aa50b83b01bfbd89008a0b39e9aa93bd6aef1f882493fad9aa0649bb"
original_class_hash = "0x5554539aa50b83b01bfbd89008a0b39e9aa93bd6aef1f882493fad9aa0649bb"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/pistols_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "pistols::systems::actions::actions"
