kind = "DojoContract"
class_hash = "0x79f095854bb34e9dd77f3970dda38fcfd1a50c601fb28683a1225db3e443d94"
original_class_hash = "0x79f095854bb34e9dd77f3970dda38fcfd1a50c601fb28683a1225db3e443d94"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/pistols_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "pistols::systems::actions::actions"
