kind = "DojoContract"
class_hash = "0x56a3eba2f65335084a2646070903bea5defe38f58fbb5c4930303a121596fe6"
original_class_hash = "0x56a3eba2f65335084a2646070903bea5defe38f58fbb5c4930303a121596fe6"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/pistols_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "pistols::systems::actions::actions"
