kind = "DojoContract"
class_hash = "0x3a74ca23371973bebe0433f7eb584bdc86403e46738d165257fc89b2d99bee0"
original_class_hash = "0x3a74ca23371973bebe0433f7eb584bdc86403e46738d165257fc89b2d99bee0"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/pistols_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "pistols::systems::actions::actions"
