kind = "DojoContract"
class_hash = "0x231b1f0e1dab25cc5070ff1cea5448b469584e21557ad98a4838ee0529a53c5"
original_class_hash = "0x231b1f0e1dab25cc5070ff1cea5448b469584e21557ad98a4838ee0529a53c5"
base_class_hash = "0x0"
abi = "manifests/slot/abis/base/contracts/pistols_mocks_lords_mock_lords_mock.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "pistols::mocks::lords_mock::lords_mock"
