kind = "DojoContract"
class_hash = "0x5b1e3306fd4fe34cfc4b19f95e87d3291bd4ef8e94e5325d539c450831a9a1f"
original_class_hash = "0x5b1e3306fd4fe34cfc4b19f95e87d3291bd4ef8e94e5325d539c450831a9a1f"
base_class_hash = "0x0"
abi = "manifests/slot/abis/base/contracts/pistols_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "pistols::systems::actions::actions"
